/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as dashboardSettingsRolesRouteImport } from './routes/(dashboard)/settings/roles'
import { Route as dashboardEmployeesPositionsRouteImport } from './routes/(dashboard)/employees/positions'
import { Route as dashboardEmployeesListRouteImport } from './routes/(dashboard)/employees/list'
import { Route as dashboardEmployeesDepartmentsRouteImport } from './routes/(dashboard)/employees/departments'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsRolesRoute = dashboardSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardEmployeesPositionsRoute =
  dashboardEmployeesPositionsRouteImport.update({
    id: '/employees/positions',
    path: '/employees/positions',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardEmployeesListRoute = dashboardEmployeesListRouteImport.update({
  id: '/employees/list',
  path: '/employees/list',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardEmployeesDepartmentsRoute =
  dashboardEmployeesDepartmentsRouteImport.update({
    id: '/employees/departments',
    path: '/employees/departments',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof dashboardIndexRoute
  '/employees/departments': typeof dashboardEmployeesDepartmentsRoute
  '/employees/list': typeof dashboardEmployeesListRoute
  '/employees/positions': typeof dashboardEmployeesPositionsRoute
  '/settings/roles': typeof dashboardSettingsRolesRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof dashboardIndexRoute
  '/employees/departments': typeof dashboardEmployeesDepartmentsRoute
  '/employees/list': typeof dashboardEmployeesListRoute
  '/employees/positions': typeof dashboardEmployeesPositionsRoute
  '/settings/roles': typeof dashboardSettingsRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/employees/departments': typeof dashboardEmployeesDepartmentsRoute
  '/(dashboard)/employees/list': typeof dashboardEmployeesListRoute
  '/(dashboard)/employees/positions': typeof dashboardEmployeesPositionsRoute
  '/(dashboard)/settings/roles': typeof dashboardSettingsRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/sign-in'
    | '/'
    | '/employees/departments'
    | '/employees/list'
    | '/employees/positions'
    | '/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/'
    | '/employees/departments'
    | '/employees/list'
    | '/employees/positions'
    | '/settings/roles'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/auth/sign-in'
    | '/(dashboard)/'
    | '/(dashboard)/employees/departments'
    | '/(dashboard)/employees/list'
    | '/(dashboard)/employees/positions'
    | '/(dashboard)/settings/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/roles': {
      id: '/(dashboard)/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof dashboardSettingsRolesRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/employees/positions': {
      id: '/(dashboard)/employees/positions'
      path: '/employees/positions'
      fullPath: '/employees/positions'
      preLoaderRoute: typeof dashboardEmployeesPositionsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/employees/list': {
      id: '/(dashboard)/employees/list'
      path: '/employees/list'
      fullPath: '/employees/list'
      preLoaderRoute: typeof dashboardEmployeesListRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/employees/departments': {
      id: '/(dashboard)/employees/departments'
      path: '/employees/departments'
      fullPath: '/employees/departments'
      preLoaderRoute: typeof dashboardEmployeesDepartmentsRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardEmployeesDepartmentsRoute: typeof dashboardEmployeesDepartmentsRoute
  dashboardEmployeesListRoute: typeof dashboardEmployeesListRoute
  dashboardEmployeesPositionsRoute: typeof dashboardEmployeesPositionsRoute
  dashboardSettingsRolesRoute: typeof dashboardSettingsRolesRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardEmployeesDepartmentsRoute: dashboardEmployeesDepartmentsRoute,
  dashboardEmployeesListRoute: dashboardEmployeesListRoute,
  dashboardEmployeesPositionsRoute: dashboardEmployeesPositionsRoute,
  dashboardSettingsRolesRoute: dashboardSettingsRolesRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
